### ISSUE TITLE
有关查询界面缩放问题

### ISSUE THREAD

**Issue by haohaolalahao** [lee88688/dataset#1]
文档查询界面缩放比例较小，作者可否增添比例缩放的功能？
![image](https://user-images.githubusercontent.com/30471665/112476681-208e7e00-8dad-11eb-8c51-5aa316828abb.png)

**Comment by lee88688** [comment]
目前网页能够缩放的方法会让整个网页变大，会增加横向滚动，这样浏览器来应该更加不方便。dash的文档就是从原网页上面直接扒下来的，你去官方看到的页面应该也是这么小。
